---
title: "BART comp model data prep"
author: "Laura Hirello"
date: "2025-07-10"
output: 
  html_document: 
    keep_md: true
---

```{r, eval=TRUE}
#Data cleaning
library(dplyr) 
library(data.table)
library("readxl")
library(tidyverse)
library(foreach)
library(readr)
library("writexl")
library(tibble)

#visualization
library(ggplot2)
library(ggpubr)
library(visreg)

#modelling
library(lme4)
library(lmerTest)

#read data
bart_df <- read_excel("bart_df.xlsx")

bart_df <- bart_df %>%
  select(-date, -time, -blockcode, -trialnum, -timebefore1stpump, -rotation, -d_n, -totalearningsBART, -ballooncount,   -explosionpoint, -wantedpumps, -pumpresult) %>% #remove unneeded columns
  mutate(subjID = paste0(participant, shift, activity)) %>% #Add in unique subject x trial identifier
  relocate(subjID, .before = participant) %>% #move subjID to the front (personal preference)
  dplyr::rename(pumps = pumpcount) #rename column as needed to match model files

anyNA(bart_df)

write_tsv(bart_df, "df.tsv")

subset_df <- bart_df %>%
  filter(participant %in% c("16"))

write_tsv(subset_df, "subset_df.tsv")

```



```{r}
library(hBayesDM)
library(rstan)
library(tictoc)
library(blastula)

rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())

#code if using the hBayesDM package
dataPath = system.file("subset_df.tsv", package="hBayesDM") #for the hBayesDM stan model without any changes
fit <- sampling(mod, data = "subset_df.tsv", chains = 4, iter = 2000)

tic()
output8_2k <- bart_par4(data="subset_df.tsv", niter=2000, nwarmup=1000, nchain=4, ncore=4) 
saveRDS(output8_2k, file = "bart_par4_output8_2k.rds")
toc()

#check model outputs
output8_2k$allIndPars
output8_2k$fit
plot(outputXX_Yk, type="trace", fontSize=11)
plot(output8_2k, type="trace", inc_warmup=T)   # traceplot of hyper parameters w/ warmup samples

plotInd(output3_2k, "phi")
plotInd(output3_2k, "eta")
plotInd(output8_2k, "gam")
plotInd(output3_2k, "tau")

```



```{r}

#Code if you are using a .stan model from github
setwd("C:/Users/laura/OneDrive/Documents/GitHub/BART-comp-model")

stan_file <- file.path("models", "asap_bart_ewmv.stan")
mod <- stan_model(file = stan_file)

subset_df <- subset_df %>%
  arrange(subjID)

subjects <- unique(subset_df$subjID) # Get unique subjects
N <- length(subjects)

trials_per_subject <- subset_df %>% # Get number of trials per subject:
  group_by(subjID) %>%
  summarise(n_trials = n())

T <- max(trials_per_subject$n_trials)
Tsubj <- trials_per_subject$n_trials

P <- 128  # max pumps + 1 (127 + 1)

subset_df <- subset_df %>% # Create trial numbers for each subject assuming rows are ordered by trial within subjID
  group_by(subjID) %>%
  mutate(trial = row_number()) %>%
  ungroup()

pumps <- subset_df %>% # Reshape to wide format for pumps and explosion
  select(subjID, trial, pumps) %>%
  pivot_wider(names_from = trial, values_from = pumps) %>%
  select(-subjID) %>%
  as.matrix()
explosion <- subset_df %>%
  select(subjID, trial, explosion) %>%
  pivot_wider(names_from = trial, values_from = explosion) %>%
  select(-subjID) %>%
  as.matrix()

data_list <- list(
  N = N,
  T = T,
  Tsubj = Tsubj,
  P = P,
  pumps = pumps,
  explosion = explosion
)

tic()
output127 <- sampling( #run the actual models
  object = mod,
  data = data_list,
  chains = 4,
  iter = 2000,
  warmup = 1000,
  seed = 123
)
toc()

saveRDS(output127, file = "outputs/asap_bart_output127.rds")

#get results from model
posterior_samples <- rstan::extract(output24)
phi_means    <- apply(posterior_samples$phi,    2, mean)
eta_means    <- apply(posterior_samples$eta,    2, mean)
rho_means    <- apply(posterior_samples$rho,    2, mean)
tau_means    <- apply(posterior_samples$tau,    2, mean)
lambda_means <- apply(posterior_samples$lambda, 2, mean)
N <- dim(posterior_samples$phi)[2]  # or just hard-code if you know N

param_summary <- data.frame(
  subjID = 1:N,
  phi = phi_means,
  eta = eta_means,
  rho = rho_means,
  tau = tau_means,
  lambda = lambda_means
)

print(param_summary)


```

